#!/bin/bash


#Add homedir for python packages
#export PYTHONPATH=$PYTHONPATH:~/py-lib:~/bin

#256 colors term
export TERM=xterm-256color

#Add GEM_HOME
export GEM_HOME="$HOME/.gem/"

# Add in the ~/bin in home directory to the path
export PATH=~/local/bin:~/bin:$PATH:$HOME/.gem/bin
