#!/bin/bash

# Add in the ~/bin in home directory to the path
#export PATH=~/bin:$PATH

#Add homedir for python packages
#export PYTHONPATH=$PYTHONPATH:~/py-lib:~/bin

#256 colors term
#export TERM=xterm-256color
